# Generated by Django 5.1.4 on 2025-07-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0007_player_trade_cooldown_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'managed': True, 'verbose_name': 'denomball', 'verbose_name_plural': 'denomballs'},
        ),
        migrations.AlterModelOptions(
            name='ballinstance',
            options={'managed': True, 'verbose_name': 'denomball instance'},
        ),
        migrations.AlterField(
            model_name='ball',
            name='country',
            field=models.CharField(max_length=48, unique=True, verbose_name='Name'),
        ),
    ]
